export enum NAMESPACES {
    HTML = 'http://www.w3.org/1999/xhtml',
    MATHML = 'http://www.w3.org/1998/Math/MathML',
    SVG = 'http://www.w3.org/2000/svg',
    XLINK = 'http://www.w3.org/1999/xlink',
    XML = 'http://www.w3.org/XML/1998/namespace',
    XMLNS = 'http://www.w3.org/2000/xmlns/',
}

const NS = NAMESPACES;

export enum ATTRS {
    TYPE = 'type',
    ACTION = 'action',
    ENCODING = 'encoding',
    PROMPT = 'prompt',
    NAME = 'name',
    COLOR = 'color',
    FACE = 'face',
    SIZE = 'size',
}

export enum DOCUMENT_MODE {
    NO_QUIRKS = 'no-quirks',
    QUIRKS = 'quirks',
    LIMITED_QUIRKS = 'limited-quirks',
}

export enum TAG_NAMES {
    A = 'a',
    ADDRESS = 'address',
    ANNOTATION_XML = 'annotation-xml',
    APPLET = 'applet',
    AREA = 'area',
    ARTICLE = 'article',
    ASIDE = 'aside',

    B = 'b',
    BASE = 'base',
    BASEFONT = 'basefont',
    BGSOUND = 'bgsound',
    BIG = 'big',
    BLOCKQUOTE = 'blockquote',
    BODY = 'body',
    BR = 'br',
    BUTTON = 'button',

    CAPTION = 'caption',
    CENTER = 'center',
    CODE = 'code',
    COL = 'col',
    COLGROUP = 'colgroup',

    DD = 'dd',
    DESC = 'desc',
    DETAILS = 'details',
    DIALOG = 'dialog',
    DIR = 'dir',
    DIV = 'div',
    DL = 'dl',
    DT = 'dt',

    EM = 'em',
    EMBED = 'embed',

    FIELDSET = 'fieldset',
    FIGCAPTION = 'figcaption',
    FIGURE = 'figure',
    FONT = 'font',
    FOOTER = 'footer',
    FOREIGN_OBJECT = 'foreignObject',
    FORM = 'form',
    FRAME = 'frame',
    FRAMESET = 'frameset',

    H1 = 'h1',
    H2 = 'h2',
    H3 = 'h3',
    H4 = 'h4',
    H5 = 'h5',
    H6 = 'h6',
    HEAD = 'head',
    HEADER = 'header',
    HGROUP = 'hgroup',
    HR = 'hr',
    HTML = 'html',

    I = 'i',
    IMG = 'img',
    IMAGE = 'image',
    INPUT = 'input',
    IFRAME = 'iframe',

    KEYGEN = 'keygen',

    LABEL = 'label',
    LI = 'li',
    LINK = 'link',
    LISTING = 'listing',

    MAIN = 'main',
    MALIGNMARK = 'malignmark',
    MARQUEE = 'marquee',
    MATH = 'math',
    MENU = 'menu',
    META = 'meta',
    MGLYPH = 'mglyph',
    MI = 'mi',
    MO = 'mo',
    MN = 'mn',
    MS = 'ms',
    MTEXT = 'mtext',

    NAV = 'nav',
    NOBR = 'nobr',
    NOFRAMES = 'noframes',
    NOEMBED = 'noembed',
    NOSCRIPT = 'noscript',

    OBJECT = 'object',
    OL = 'ol',
    OPTGROUP = 'optgroup',
    OPTION = 'option',

    P = 'p',
    PARAM = 'param',
    PLAINTEXT = 'plaintext',
    PRE = 'pre',

    RB = 'rb',
    RP = 'rp',
    RT = 'rt',
    RTC = 'rtc',
    RUBY = 'ruby',

    S = 's',
    SCRIPT = 'script',
    SECTION = 'section',
    SELECT = 'select',
    SOURCE = 'source',
    SMALL = 'small',
    SPAN = 'span',
    STRIKE = 'strike',
    STRONG = 'strong',
    STYLE = 'style',
    SUB = 'sub',
    SUMMARY = 'summary',
    SUP = 'sup',

    TABLE = 'table',
    TBODY = 'tbody',
    TEMPLATE = 'template',
    TEXTAREA = 'textarea',
    TFOOT = 'tfoot',
    TD = 'td',
    TH = 'th',
    THEAD = 'thead',
    TITLE = 'title',
    TR = 'tr',
    TRACK = 'track',
    TT = 'tt',

    U = 'u',
    UL = 'ul',

    SVG = 'svg',

    VAR = 'var',

    WBR = 'wbr',

    XMP = 'xmp',
}

const $ = TAG_NAMES;

export const SPECIAL_ELEMENTS = {
    [NS.HTML]: new Set([
        $.ADDRESS,
        $.APPLET,
        $.AREA,
        $.ARTICLE,
        $.ASIDE,
        $.BASE,
        $.BASEFONT,
        $.BGSOUND,
        $.BLOCKQUOTE,
        $.BODY,
        $.BR,
        $.BUTTON,
        $.CAPTION,
        $.CENTER,
        $.COL,
        $.COLGROUP,
        $.DD,
        $.DETAILS,
        $.DIR,
        $.DIV,
        $.DL,
        $.DT,
        $.EMBED,
        $.FIELDSET,
        $.FIGCAPTION,
        $.FIGURE,
        $.FOOTER,
        $.FORM,
        $.FRAME,
        $.FRAMESET,
        $.H1,
        $.H2,
        $.H3,
        $.H4,
        $.H5,
        $.H6,
        $.HEAD,
        $.HEADER,
        $.HGROUP,
        $.HR,
        $.HTML,
        $.IFRAME,
        $.IMG,
        $.INPUT,
        $.LI,
        $.LINK,
        $.LISTING,
        $.MAIN,
        $.MARQUEE,
        $.MENU,
        $.META,
        $.NAV,
        $.NOEMBED,
        $.NOFRAMES,
        $.NOSCRIPT,
        $.OBJECT,
        $.OL,
        $.P,
        $.PARAM,
        $.PLAINTEXT,
        $.PRE,
        $.SCRIPT,
        $.SECTION,
        $.SELECT,
        $.SOURCE,
        $.STYLE,
        $.SUMMARY,
        $.TABLE,
        $.TBODY,
        $.TD,
        $.TEMPLATE,
        $.TEXTAREA,
        $.TFOOT,
        $.TH,
        $.THEAD,
        $.TITLE,
        $.TR,
        $.TRACK,
        $.UL,
        $.WBR,
        $.XMP,
    ]),
    [NS.MATHML]: new Set([$.MI, $.MO, $.MN, $.MS, $.MTEXT, $.ANNOTATION_XML]),
    [NS.SVG]: new Set([$.TITLE, $.FOREIGN_OBJECT, $.DESC]),
};
