'use strict';

const HTML = { 
    NAMESPACES: {
        HTML: 'http://www.w3.org/1999/xhtml',
        MATHML: 'http://www.w3.org/1998/Math/MathML',
        SVG: 'http://www.w3.org/2000/svg',
        XLINK: 'http://www.w3.org/1999/xlink',
        XML: 'http://www.w3.org/XML/1998/namespace',
        XMLNS: 'http://www.w3.org/2000/xmlns/'
    },
    TAG_NAMES: {
        A: 'a',
        ADDRESS: 'address',
        ANNOTATION_XML: 'annotation-xml',
        APPLET: 'applet',
        AREA: 'area',
        ARTICLE: 'article',
        ASIDE: 'aside',
    
        B: 'b',
        BASE: 'base',
        BASEFONT: 'basefont',
        BGSOUND: 'bgsound',
        BIG: 'big',
        BLOCKQUOTE: 'blockquote',
        BODY: 'body',
        BR: 'br',
        BUTTON: 'button',
    
        CAPTION: 'caption',
        CENTER: 'center',
        CODE: 'code',
        COL: 'col',
        COLGROUP: 'colgroup',
    
        DD: 'dd',
        DESC: 'desc',
        DETAILS: 'details',
        DIALOG: 'dialog',
        DIR: 'dir',
        DIV: 'div',
        DL: 'dl',
        DT: 'dt',
    
        EM: 'em',
        EMBED: 'embed',
    
        FIELDSET: 'fieldset',
        FIGCAPTION: 'figcaption',
        FIGURE: 'figure',
        FONT: 'font',
        FOOTER: 'footer',
        FOREIGN_OBJECT: 'foreignObject',
        FORM: 'form',
        FRAME: 'frame',
        FRAMESET: 'frameset',
    
        H1: 'h1',
        H2: 'h2',
        H3: 'h3',
        H4: 'h4',
        H5: 'h5',
        H6: 'h6',
        HEAD: 'head',
        HEADER: 'header',
        HGROUP: 'hgroup',
        HR: 'hr',
        HTML: 'html',
    
        I: 'i',
        IMG: 'img',
        IMAGE: 'image',
        INPUT: 'input',
        IFRAME: 'iframe',
    
        KEYGEN: 'keygen',
    
        LABEL: 'label',
        LI: 'li',
        LINK: 'link',
        LISTING: 'listing',
    
        MAIN: 'main',
        MALIGNMARK: 'malignmark',
        MARQUEE: 'marquee',
        MATH: 'math',
        MENU: 'menu',
        META: 'meta',
        MGLYPH: 'mglyph',
        MI: 'mi',
        MO: 'mo',
        MN: 'mn',
        MS: 'ms',
        MTEXT: 'mtext',
    
        NAV: 'nav',
        NOBR: 'nobr',
        NOFRAMES: 'noframes',
        NOEMBED: 'noembed',
        NOSCRIPT: 'noscript',
    
        OBJECT: 'object',
        OL: 'ol',
        OPTGROUP: 'optgroup',
        OPTION: 'option',
    
        P: 'p',
        PARAM: 'param',
        PLAINTEXT: 'plaintext',
        PRE: 'pre',
    
        RB: 'rb',
        RP: 'rp',
        RT: 'rt',
        RTC: 'rtc',
        RUBY: 'ruby',
    
        S: 's',
        SCRIPT: 'script',
        SECTION: 'section',
        SELECT: 'select',
        SOURCE: 'source',
        SMALL: 'small',
        SPAN: 'span',
        STRIKE: 'strike',
        STRONG: 'strong',
        STYLE: 'style',
        SUB: 'sub',
        SUMMARY: 'summary',
        SUP: 'sup',
    
        TABLE: 'table',
        TBODY: 'tbody',
        TEMPLATE: 'template',
        TEXTAREA: 'textarea',
        TFOOT: 'tfoot',
        TD: 'td',
        TH: 'th',
        THEAD: 'thead',
        TITLE: 'title',
        TR: 'tr',
        TRACK: 'track',
        TT: 'tt',
    
        U: 'u',
        UL: 'ul',
    
        SVG: 'svg',
    
        VAR: 'var',
    
        WBR: 'wbr',
    
        XMP: 'xmp'
    },
    SPECIAL_ELEMENTS: {
        [HTML.NAMESPACES.HTML]: {
            [HTML.TAG_NAMES.ADDRESS]: true,
            [HTML.TAG_NAMES.APPLET]: true,
            [HTML.TAG_NAMES.AREA]: true,
            [HTML.TAG_NAMES.ARTICLE]: true,
            [HTML.TAG_NAMES.ASIDE]: true,
            [HTML.TAG_NAMES.BASE]: true,
            [HTML.TAG_NAMES.BASEFONT]: true,
            [HTML.TAG_NAMES.BGSOUND]: true,
            [HTML.TAG_NAMES.BLOCKQUOTE]: true,
            [HTML.TAG_NAMES.BODY]: true,
            [HTML.TAG_NAMES.BR]: true,
            [HTML.TAG_NAMES.BUTTON]: true,
            [HTML.TAG_NAMES.CAPTION]: true,
            [HTML.TAG_NAMES.CENTER]: true,
            [HTML.TAG_NAMES.COL]: true,
            [HTML.TAG_NAMES.COLGROUP]: true,
            [HTML.TAG_NAMES.DD]: true,
            [HTML.TAG_NAMES.DETAILS]: true,
            [HTML.TAG_NAMES.DIR]: true,
            [HTML.TAG_NAMES.DIV]: true,
            [HTML.TAG_NAMES.DL]: true,
            [HTML.TAG_NAMES.DT]: true,
            [HTML.TAG_NAMES.EMBED]: true,
            [HTML.TAG_NAMES.FIELDSET]: true,
            [HTML.TAG_NAMES.FIGCAPTION]: true,
            [HTML.TAG_NAMES.FIGURE]: true,
            [HTML.TAG_NAMES.FOOTER]: true,
            [HTML.TAG_NAMES.FORM]: true,
            [HTML.TAG_NAMES.FRAME]: true,
            [HTML.TAG_NAMES.FRAMESET]: true,
            [HTML.TAG_NAMES.H1]: true,
            [HTML.TAG_NAMES.H2]: true,
            [HTML.TAG_NAMES.H3]: true,
            [HTML.TAG_NAMES.H4]: true,
            [HTML.TAG_NAMES.H5]: true,
            [HTML.TAG_NAMES.H6]: true,
            [HTML.TAG_NAMES.HEAD]: true,
            [HTML.TAG_NAMES.HEADER]: true,
            [HTML.TAG_NAMES.HGROUP]: true,
            [HTML.TAG_NAMES.HR]: true,
            [HTML.TAG_NAMES.HTML]: true,
            [HTML.TAG_NAMES.IFRAME]: true,
            [HTML.TAG_NAMES.IMG]: true,
            [HTML.TAG_NAMES.INPUT]: true,
            [HTML.TAG_NAMES.LI]: true,
            [HTML.TAG_NAMES.LINK]: true,
            [HTML.TAG_NAMES.LISTING]: true,
            [HTML.TAG_NAMES.MAIN]: true,
            [HTML.TAG_NAMES.MARQUEE]: true,
            [HTML.TAG_NAMES.MENU]: true,
            [HTML.TAG_NAMES.META]: true,
            [HTML.TAG_NAMES.NAV]: true,
            [HTML.TAG_NAMES.NOEMBED]: true,
            [HTML.TAG_NAMES.NOFRAMES]: true,
            [HTML.TAG_NAMES.NOSCRIPT]: true,
            [HTML.TAG_NAMES.OBJECT]: true,
            [HTML.TAG_NAMES.OL]: true,
            [HTML.TAG_NAMES.P]: true,
            [HTML.TAG_NAMES.PARAM]: true,
            [HTML.TAG_NAMES.PLAINTEXT]: true,
            [HTML.TAG_NAMES.PRE]: true,
            [HTML.TAG_NAMES.SCRIPT]: true,
            [HTML.TAG_NAMES.SECTION]: true,
            [HTML.TAG_NAMES.SELECT]: true,
            [HTML.TAG_NAMES.SOURCE]: true,
            [HTML.TAG_NAMES.STYLE]: true,
            [HTML.TAG_NAMES.SUMMARY]: true,
            [HTML.TAG_NAMES.TABLE]: true,
            [HTML.TAG_NAMES.TBODY]: true,
            [HTML.TAG_NAMES.TD]: true,
            [HTML.TAG_NAMES.TEMPLATE]: true,
            [HTML.TAG_NAMES.TEXTAREA]: true,
            [HTML.TAG_NAMES.TFOOT]: true,
            [HTML.TAG_NAMES.TH]: true,
            [HTML.TAG_NAMES.THEAD]: true,
            [HTML.TAG_NAMES.TITLE]: true,
            [HTML.TAG_NAMES.TR]: true,
            [HTML.TAG_NAMES.TRACK]: true,
            [HTML.TAG_NAMES.UL]: true,
            [HTML.TAG_NAMES.WBR]: true,
            [HTML.TAG_NAMES.XMP]: true
        },
        [HTML.NAMESPACES.MATHML]: {
            [HTML.TAG_NAMES.MI]: true,
            [HTML.TAG_NAMES.MO]: true,
            [HTML.TAG_NAMES.MN]: true,
            [HTML.TAG_NAMES.MS]: true,
            [HTML.TAG_NAMES.MTEXT]: true,
            [HTML.TAG_NAMES.ANNOTATION_XML]: true
        },
        [HTML.NAMESPACES.SVG]: {
            [HTML.TAG_NAMES.TITLE]: true,
            [HTML.TAG_NAMES.FOREIGN_OBJECT]: true,
            [HTML.TAG_NAMES.DESC]: true
        }
    },
    ATTRS: {
        TYPE: 'type',
        ACTION: 'action',
        ENCODING: 'encoding',
        PROMPT: 'prompt',
        NAME: 'name',
        COLOR: 'color',
        FACE: 'face',
        SIZE: 'size'
    },
    DOCUMENT_MODE: {
        NO_QUIRKS: 'no-quirks',
        QUIRKS: 'quirks',
        LIMITED_QUIRKS: 'limited-quirks'
    }
}

module.exports = HTML