var NAMESPACES = exports.NAMESPACES = {
    HTML: 'http://www.w3.org/1999/xhtml',
    MATHML: 'http://www.w3.org/1998/Math/MathML',
    SVG: 'http://www.w3.org/2000/svg',
    XLINK: 'http://www.w3.org/1999/xlink',
    XML: 'http://www.w3.org/XML/1998/namespace',
    XMLNS: 'http://www.w3.org/2000/xmlns/'
};

exports.TAG_NAMES = {
    ADDRESS: 'address',
    ARTICLE: 'article',
    ASIDE: 'aside',
    BLOCKQUOTE: 'blockquote',
    CENTER: 'center',
    DETAILS: 'details',
    DIALOG: 'dialog',
    DIR: 'dir',
    DIV: 'div',
    DD: 'dd',
    DT: 'dt',
    DL: 'dl',
    FIELDSET: 'fieldset',
    FIGCAPTION: 'figcaption',
    FIGURE: 'figure',
    FORM: 'form',
    FOOTER: 'footer',
    HEADER: 'header',
    HGROUP: 'hgroup',
    MAIN: 'main',
    MENU: 'menu',
    NAV: 'nav',
    P: 'p',
    PRE: 'pre',
    SECTION: 'section',
    SUMMARY: 'summary',
    HTML: 'html',
    HEAD: 'head',
    BODY: 'body',
    BR: 'br',
    BASE: 'base',
    BASEFONT: 'basefont',
    BGSOUND: 'bgsound',
    BUTTON: 'button',
    META: 'meta',
    LI: 'li',
    LINK: 'link',
    LISTING: 'listing',
    SCRIPT: 'script',
    STYLE: 'style',
    TITLE: 'title',
    FRAMESET: 'frameset',
    NOSCRIPT: 'noscript',
    NOFRAMES: 'noframes',
    MENUITEM: 'menuitem',
    OL: 'ol',
    UL: 'ul',
    TABLE: 'table',
    OPTION: 'option',
    OPTGROUP: 'optgroup',
    PLAINTEXT: 'plaintext',
    H1: 'h1',
    H2: 'h2',
    H3: 'h3',
    H4: 'h4',
    H5: 'h5',
    H6: 'h6'
};

var SPECIAL_ELEMENTS = {
    'address': NAMESPACES.HTML,
    'applet': NAMESPACES.HTML,
    'area': NAMESPACES.HTML,
    'article': NAMESPACES.HTML,
    'aside': NAMESPACES.HTML,
    'base': NAMESPACES.HTML,
    'basefont': NAMESPACES.HTML,
    'bgsound': NAMESPACES.HTML,
    'blockquote': NAMESPACES.HTML,
    'body': NAMESPACES.HTML,
    'br': NAMESPACES.HTML,
    'button': NAMESPACES.HTML,
    'caption': NAMESPACES.HTML,
    'center': NAMESPACES.HTML,
    'col': NAMESPACES.HTML,
    'colgroup': NAMESPACES.HTML,
    'dd': NAMESPACES.HTML,
    'details': NAMESPACES.HTML,
    'dir': NAMESPACES.HTML,
    'div': NAMESPACES.HTML,
    'dl': NAMESPACES.HTML,
    'dt': NAMESPACES.HTML,
    'embed': NAMESPACES.HTML,
    'fieldset': NAMESPACES.HTML,
    'figcaption': NAMESPACES.HTML,
    'figure': NAMESPACES.HTML,
    'footer': NAMESPACES.HTML,
    'form': NAMESPACES.HTML,
    'frame': NAMESPACES.HTML,
    'frameset': NAMESPACES.HTML,
    'h1': NAMESPACES.HTML,
    'h2': NAMESPACES.HTML,
    'h3': NAMESPACES.HTML,
    'h4': NAMESPACES.HTML,
    'h5': NAMESPACES.HTML,
    'h6': NAMESPACES.HTML,
    'head': NAMESPACES.HTML,
    'header': NAMESPACES.HTML,
    'hgroup': NAMESPACES.HTML,
    'hr': NAMESPACES.HTML,
    'html': NAMESPACES.HTML,
    'iframe': NAMESPACES.HTML,
    'img': NAMESPACES.HTML,
    'input': NAMESPACES.HTML,
    'isindex': NAMESPACES.HTML,
    'li': NAMESPACES.HTML,
    'link': NAMESPACES.HTML,
    'listing': NAMESPACES.HTML,
    'main': NAMESPACES.HTML,
    'marquee': NAMESPACES.HTML,
    'menu': NAMESPACES.HTML,
    'menuitem': NAMESPACES.HTML,
    'meta': NAMESPACES.HTML,
    'nav': NAMESPACES.HTML,
    'noembed': NAMESPACES.HTML,
    'noframes': NAMESPACES.HTML,
    'noscript': NAMESPACES.HTML,
    'object': NAMESPACES.HTML,
    'ol': NAMESPACES.HTML,
    'p': NAMESPACES.HTML,
    'param': NAMESPACES.HTML,
    'plaintext': NAMESPACES.HTML,
    'pre': NAMESPACES.HTML,
    'script': NAMESPACES.HTML,
    'section': NAMESPACES.HTML,
    'select': NAMESPACES.HTML,
    'source': NAMESPACES.HTML,
    'style': NAMESPACES.HTML,
    'summary': NAMESPACES.HTML,
    'table': NAMESPACES.HTML,
    'tbody': NAMESPACES.HTML,
    'td': NAMESPACES.HTML,
    'textarea': NAMESPACES.HTML,
    'tfoot': NAMESPACES.HTML,
    'th': NAMESPACES.HTML,
    'thead': NAMESPACES.HTML,
    'title': [NAMESPACES.HTML, NAMESPACES.SVG],
    'tr': NAMESPACES.HTML,
    'track': NAMESPACES.HTML,
    'ul': NAMESPACES.HTML,
    'wbr': NAMESPACES.HTML,
    'xmp': NAMESPACES.HTML,
    'mi': NAMESPACES.MATHML,
    'mo': NAMESPACES.MATHML,
    'mn': NAMESPACES.MATHML,
    'ms': NAMESPACES.MATHML,
    'mtext': NAMESPACES.MATHML,
    'annotation-xml': NAMESPACES.MATHML,
    'foreignObject': NAMESPACES.SVG,
    'desc': NAMESPACES.SVG
};

var SCOPING_ELEMENTS = {
    'applet': NAMESPACES.HTML,
    'caption': NAMESPACES.HTML,
    'html': NAMESPACES.HTML,
    'table': NAMESPACES.HTML,
    'td': NAMESPACES.HTML,
    'th': NAMESPACES.HTML,
    'marquee': NAMESPACES.HTML,
    'object': NAMESPACES.HTML,
    'mi': NAMESPACES.MATHML,
    'mo': NAMESPACES.MATHML,
    'mn': NAMESPACES.MATHML,
    'ms': NAMESPACES.MATHML,
    'mtext': NAMESPACES.MATHML,
    'annotation-xml': NAMESPACES.MATHML,
    'foreignObject': NAMESPACES.SVG,
    'desc': NAMESPACES.SVG,
    'title': NAMESPACES.SVG
};

exports.isScoping = function (element) {
    return SCOPING_ELEMENTS[element.tagName] === element.namespaceURI;
};

exports.isSpecial = function (element) {
    var ns = SCOPING_ELEMENTS[element.tagName];

    return ns && ns.indexOf(element.namespaceURI) > -1;
};