var NAMESPACES = exports.NAMESPACES = {
    HTML: 'http://www.w3.org/1999/xhtml',
    MATHML: 'http://www.w3.org/1998/Math/MathML',
    SVG: 'http://www.w3.org/2000/svg',
    XLINK: 'http://www.w3.org/1999/xlink',
    XML: 'http://www.w3.org/XML/1998/namespace',
    XMLNS: 'http://www.w3.org/2000/xmlns/'
};

exports.TAG_NAMES = {
    ADDRESS: 'address',
    ARTICLE: 'article',
    ASIDE: 'aside',
    BLOCKQUOTE: 'blockquote',
    CENTER: 'center',
    DETAILS: 'details',
    DIALOG: 'dialog',
    DIR: 'dir',
    DIV: 'div',
    DL: 'dl',
    FIELDSET: 'fieldset',
    FIGCAPTION: 'figcaption',
    FIGURE: 'figure',
    FOOTER: 'footer',
    HEADER: 'header',
    HGROUP: 'hgroup',
    MAIN: 'main',
    MENU: 'menu',
    NAV: 'nav',
    P: 'p',
    SECTION: 'section',
    SUMMARY: 'summary',
    HTML: 'html',
    HEAD: 'head',
    BODY: 'body',
    BR: 'br',
    BASE: 'base',
    BASEFONT: 'basefont',
    BGSOUND: 'bgsound',
    BUTTON: 'button',
    META: 'meta',
    LINK: 'link',
    SCRIPT: 'script',
    STYLE: 'style',
    TITLE: 'title',
    FRAMESET: 'frameset',
    NOSCRIPT: 'noscript',
    NOFRAMES: 'noframes',
    MENUITEM: 'menuitem',
    OL: 'ol',
    UL: 'ul',
    TABLE: 'table',
    OPTION: 'option',
    OPTGROUP: 'optgroup'
};

exports.SCOPING_ELEMENTS = {
    'applet': NAMESPACES.HTML,
    'caption': NAMESPACES.HTML,
    'html': NAMESPACES.HTML,
    'table': NAMESPACES.HTML,
    'td': NAMESPACES.HTML,
    'th': NAMESPACES.HTML,
    'marquee': NAMESPACES.HTML,
    'object': NAMESPACES.HTML,
    'mi': NAMESPACES.MATHML,
    'mo': NAMESPACES.MATHML,
    'mn': NAMESPACES.MATHML,
    'ms': NAMESPACES.MATHML,
    'mtext': NAMESPACES.MATHML,
    'annotation-xml': NAMESPACES.MATHML,
    'foreignObject': NAMESPACES.SVG,
    'desc': NAMESPACES.SVG,
    'title': NAMESPACES.SVG
};