exports.UNEXPECTED_NULL_CHARACTER = 'UNEXPECTED_NULL_CHARACTER';
exports.BOGUS_COMMENT = 'BOGUS_COMMENT';
exports.BOGUS_TAG_DECLARATION = 'BOGUS_TAG_DECLARATION';
exports.MISSING_END_TAG_NAME = 'MISSING_END_TAG_NAME';
exports.EOF_IN_END_TAG_NAME = 'EOF_IN_END_TAG_NAME';