exports.UNEXPECTED_NULL_CHARACTER = 'UNEXPECTED_NULL_CHARACTER';
exports.BOGUS_COMMENT = 'BOGUS_COMMENT';
exports.UNEXPECTED_CHARACTER_IN_TAG_NAME = 'UNEXPECTED_CHARACTER_IN_TAG_NAME';
exports.MISSING_END_TAG_NAME = 'MISSING_END_TAG_NAME';
exports.EOF_IN_TAG_NAME = 'EOF_IN_TAG_NAME';