var html = require('./html');

//Aliases
var $ = html.TAG_NAMES,
    NAMESPACES = html.NAMESPACES;

//TODO use consts here for tagNames
exports.SPECIAL_ELEMENTS = {
    'address': NAMESPACES.HTML,
    'applet': NAMESPACES.HTML,
    'area': NAMESPACES.HTML,
    'article': NAMESPACES.HTML,
    'aside': NAMESPACES.HTML,
    'base': NAMESPACES.HTML,
    'basefont': NAMESPACES.HTML,
    'bgsound': NAMESPACES.HTML,
    'blockquote': NAMESPACES.HTML,
    'body': NAMESPACES.HTML,
    'br': NAMESPACES.HTML,
    'button': NAMESPACES.HTML,
    'caption': NAMESPACES.HTML,
    'center': NAMESPACES.HTML,
    'col': NAMESPACES.HTML,
    'colgroup': NAMESPACES.HTML,
    'dd': NAMESPACES.HTML,
    'details': NAMESPACES.HTML,
    'dir': NAMESPACES.HTML,
    'div': NAMESPACES.HTML,
    'dl': NAMESPACES.HTML,
    'dt': NAMESPACES.HTML,
    'embed': NAMESPACES.HTML,
    'fieldset': NAMESPACES.HTML,
    'figcaption': NAMESPACES.HTML,
    'figure': NAMESPACES.HTML,
    'footer': NAMESPACES.HTML,
    'form': NAMESPACES.HTML,
    'frame': NAMESPACES.HTML,
    'frameset': NAMESPACES.HTML,
    'h1': NAMESPACES.HTML,
    'h2': NAMESPACES.HTML,
    'h3': NAMESPACES.HTML,
    'h4': NAMESPACES.HTML,
    'h5': NAMESPACES.HTML,
    'h6': NAMESPACES.HTML,
    'head': NAMESPACES.HTML,
    'header': NAMESPACES.HTML,
    'hgroup': NAMESPACES.HTML,
    'hr': NAMESPACES.HTML,
    'html': NAMESPACES.HTML,
    'iframe': NAMESPACES.HTML,
    'img': NAMESPACES.HTML,
    'input': NAMESPACES.HTML,
    'isindex': NAMESPACES.HTML,
    'li': NAMESPACES.HTML,
    'link': NAMESPACES.HTML,
    'listing': NAMESPACES.HTML,
    'main': NAMESPACES.HTML,
    'marquee': NAMESPACES.HTML,
    'menu': NAMESPACES.HTML,
    'menuitem': NAMESPACES.HTML,
    'meta': NAMESPACES.HTML,
    'nav': NAMESPACES.HTML,
    'noembed': NAMESPACES.HTML,
    'noframes': NAMESPACES.HTML,
    'noscript': NAMESPACES.HTML,
    'object': NAMESPACES.HTML,
    'ol': NAMESPACES.HTML,
    'p': NAMESPACES.HTML,
    'param': NAMESPACES.HTML,
    'plaintext': NAMESPACES.HTML,
    'pre': NAMESPACES.HTML,
    'script': NAMESPACES.HTML,
    'section': NAMESPACES.HTML,
    'select': NAMESPACES.HTML,
    'source': NAMESPACES.HTML,
    'style': NAMESPACES.HTML,
    'summary': NAMESPACES.HTML,
    'table': NAMESPACES.HTML,
    'tbody': NAMESPACES.HTML,
    'td': NAMESPACES.HTML,
    'textarea': NAMESPACES.HTML,
    'tfoot': NAMESPACES.HTML,
    'th': NAMESPACES.HTML,
    'thead': NAMESPACES.HTML,
    'title': [NAMESPACES.HTML, NAMESPACES.SVG],
    'tr': NAMESPACES.HTML,
    'track': NAMESPACES.HTML,
    'ul': NAMESPACES.HTML,
    'wbr': NAMESPACES.HTML,
    'xmp': NAMESPACES.HTML,
    'mi': NAMESPACES.MATHML,
    'mo': NAMESPACES.MATHML,
    'mn': NAMESPACES.MATHML,
    'ms': NAMESPACES.MATHML,
    'mtext': NAMESPACES.MATHML,
    'annotation-xml': NAMESPACES.MATHML,
    'foreignObject': NAMESPACES.SVG,
    'desc': NAMESPACES.SVG
};

var CAN_REMAIN_OPEN_AFTER_BODY = exports.CAN_REMAIN_OPEN_AFTER_BODY = {};
CAN_REMAIN_OPEN_AFTER_BODY[$.DD] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.DT] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.LI] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.OPTGROUP] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.OPTION] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.P] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.RP] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.RT] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.TBODY] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.TD] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.TFOOT] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.TH] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.THEAD] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.TR] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.BODY] = true;
CAN_REMAIN_OPEN_AFTER_BODY[$.HTML] = true;

var NOT_ALLOWED_IN_FOREIGN_CONTENT = exports.NOT_ALLOWED_IN_FOREIGN_CONTENT = {};
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.B] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.BIG] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.BLOCKQUOTE] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.BODY] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.BR] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.CENTER] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.CODE] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.DD] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.DIV] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.DL] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.DT] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.EM] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.EMBED] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.H1] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.H2] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.H3] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.H4] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.H5] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.H6] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.HEAD] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.HR] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.I] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.IMG] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.LI] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.LISTING] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.MENU] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.META] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.NOBR] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.OL] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.P] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.PRE] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.RUBY] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.S] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.SMALL] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.SPAN] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.STRONG] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.STRIKE] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.SUB] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.SUP] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.TABLE] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.TT] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.U] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.UL] = true;
NOT_ALLOWED_IN_FOREIGN_CONTENT[$.VAR] = true;
