name: Deploy to GitHub Pages
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: lts/*
                  cache: npm
            - run: npm ci
            - name: Build docs
              run: npm run build:docs
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/build
                  cname: parse5.js.org
